config/routes.rb
FlitterMysql::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :upload, :only => [:upload]

  root :to => "pages#home"

  match '/contact',                 :to => 'pages#contact'
  match '/about',                   :to => 'pages#about'
  match '/flitter/user/:username',  :to => 'users#show'
  match '/users/friends/:username',    :to => 'users#relationships'
  match '/users/edit/:username',    :to => 'users#edit'
  match '/signup',                  :to => 'users#new'
  match '/signin',                  :to => 'sessions#new'
  match '/signout',                 :to => 'sessions#destroy'
  match '/feeds',                   :to => 'microposts#index'
  match '/upload',                   :to => 'upload#upload'
end

app/views/shared/_error_messages.html.erb
<% if !object.nil? && object.errors.any? %> <!-- check if the object is not nil. -->
  <div id="error_explanation" class="error">
	<h2>
		<%= pluralize(object.errors.count, "error") %>
		prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
	</h2>
	<p>Problems with the following fields:</p>
	<ul>
    	<% object.errors.full_messages.each do |message| %>
    		<li><%= message %></li>
    	<% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<div class="new-micropost">
		<%= render 'shared/error_messages', :object => @micropost %>
		<div class="form-field-no-width">
			<%= f.label :content, :class => "hidden" %>
			<%= f.text_area :content, :rows => 4, :class => "max-length-200 text-expand required", :placeholder => "What's up?" %>
			<%= f.submit "Post", :class => "check-required" %>
		</div>
	</div>
<% end %>

app/views/shared/_navigation.html.erb
<li><%= link_to('Users', users_path)  %></li>
<% if signed_in? %>
  <li>
  	<%= link_to('Profile', "/flitter/user/#{current_user.username}") %>
  </li>
  <li><%= link_to('Sign Out', signout_path, :method => :delete) %></li>
<% else %>
  <li><%= link_to('Sign In', signin_path)  %></li>
  <li><%= link_to('Sign Up New User', signup_path)  %></li>
<% end %>

app/views/shared/_signupboxes.html.erb
<div class="sign-up-boxes">
	<%= render 'users/signin' %>
	<%= render 'users/signup' %>
</div>

app/views/shared/_welcome.html.erb
<div class="welcome-note">
	<h1>Welcome to Flitter!</h1>
	<p>Sign in to open your account or sign up for free to gain access to Flitter.</p>
</div>